name = "zirconiabot"
main = "./src/server.js"
compatibility_date="2026-06-08"

[observability.logs]
enabled = true
invocation_logs = true

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID
